commerce/auctions/urls.py
from django.urls import path

from . import views

app_name = "auctions"

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create", views.create_listing, name="create_listing"),
    path("/<listing_id>", views.listing_item, name="listing_item"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("watchlist/<item_id>", views.remove_item, name="remove_item"),
    path("categories/<str:cat>/", views.category, name="category"),
    path("disable_listing/<listing_id>", views.disable_listing, name="disable_listing"),
    path("closed", views.closed_listings, name="closed_listings"),
    path("search_listing", views.search_listing, name="search_listing"),
    path("like/<pk>", views.like_comment, name="like_comment"),
    path("dislike/<pk>", views.dislike_comment, name="dislike_comment"),
]

commerce/commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commerce/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
import PIL.Image
from PIL import ImageOps
from mptt.models import MPTTModel, TreeForeignKey


class User(AbstractUser):
    profile_picture = models.ImageField(null=True, blank=True, upload_to="images/profile/")



class Auction(models.Model):

    CATEGORY_CHOICES = (
        ('accessories','Accessories'),
        ('art','Art'),
        ('bags', 'Bags'),
        ('books', 'Books'),
        ('cameras','Cameras'),
        ('cell phone accessories','Cell Phone Accessories'),
        ('cell phones','Cell Phones'),
        ('clothes','Clothes'),
        ('computers','Computers'),
        ('cosmetics','Cosmetics'),
        ('jewelry','Jewelry'),
        ('musical instruments','Musical Instruments'),
        ('sporting goods','Sporting Goods'),
        ('shoes','Shoes'),
        ('toys','Toys'),
        ('watches','Watches'),
        ('other','Other'),
    )

    product_name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    starting_bid = models.IntegerField(blank=False)
    product_category = models.CharField(choices=CATEGORY_CHOICES, max_length=50, null=True)
    product_image = models.ImageField(null=True, blank=True, upload_to="images/")
    product_owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name="owner", blank=True, null=True)
    highest_bid = models.IntegerField(blank=True, null=True)
    date_created = models.DateTimeField(blank=True, null=True, auto_now_add=True)
    active = models.BooleanField(default=True)
    date_closed = models.DateTimeField(blank=True, null=True, auto_now_add=True)

    def __str__(self):
        return self.product_name


class Watchlist(models.Model):
    watchlist_item = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="auction_item")
    watchlist_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="auction_user")

    def __str__(self):
        return self.watchlist_item.product_name


class Bid(models.Model):
    auction_biding = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="auction_bid")
    new_bid = models.CharField(blank=True, null=True, max_length=100)
    bidder = models.ForeignKey(User, on_delete=models.CASCADE, related_name="auction_bidder", blank=True, null=True)

    def __str__(self):
        return f"{self.auction_biding.product_name}: ${self.new_bid}"


class Comment(MPTTModel):
    product = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="comments")
    name = models.ForeignKey(User, on_delete=models.CASCADE, related_name="commentator")
    body = models.TextField(blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name="comment_likes", blank=True, null=True,)
    dislikes = models.ManyToManyField(User, related_name="comment_dislikes", blank=True, null=True,)
    parent = TreeForeignKey("self", on_delete=models.CASCADE, blank=True, null=True, related_name="children")


    class MPTTMeta:
        order_insertion_by = ['date_added']

    def __str__(self):
        return f"{self.name} commented {self.product}: {self.body}"

    def total_likes(self):
        return self.likes.count()

    def total_dislikes(self):
        return self.dislikes.count()



class Image(models.Model):
    auction = models.ForeignKey(Auction, on_delete=models.CASCADE, related_name="auction_images")
    image = models.ImageField(default='default.jpg', blank=True, null=True, upload_to="images/")



commerce/auctions/forms.py
from django import forms
from django.forms import ModelForm
from .models import Auction, Comment, User, Bid, Image



class AuctionForm(ModelForm):
    class Meta:
        model = Auction
        fields = ('product_name', 'product_category', 'starting_bid', 'description')

        labels = {
            'product_name':'Product Name',
            'product_category':'Category',
            'starting_bid':'Starting Bid',
            'description':'Product Description',
        }

        widgets = {
            'product_name': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Product Name', 'autocomplete': 'off'}),
            'product_category': forms.Select(attrs={'class':'form-control', 'placeholder':'Product Category', 'autocomplete': 'off'}),
            'starting_bid': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Starting Bid', 'autocomplete': 'off'}),
            'description': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Description', 'autocomplete': 'off'}),
        }


class ImageForm(ModelForm):
    image = forms.ImageField(
        label='Image',
        widget=forms.ClearableFileInput(attrs={"multiple":True}),
    )

    class Meta:
        model = Image
        fields = ('image',)



class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ('body', )

        labels = {
            'body':'',
            }


        widgets = {
            'body': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Comment', 'rows':6, 'class':'comment_form'}),
        }


class BidForm(ModelForm):
    class Meta:
        model = Bid
        fields = ('new_bid', )

        labels = {
            'new_bid':'',
            }

        widgets = {
            'new_bid': forms.TextInput(attrs={'class':'form-control', 'placeholder':'New Bid', 'autocomplete': 'off'}),
        }

commerce/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from .models import User, Auction, Watchlist, Bid, Comment, Image
from .forms import AuctionForm, CommentForm, BidForm, ImageForm
from django.contrib import messages
import datetime
from django.core.paginator import Paginator


def index(request):
    listings = Auction.objects.all()
    listings = listings.filter(active = True)
    listings = listings.order_by("-date_created").all()

    # Set up Paginaton
    p = Paginator(listings, 10)
    page = request.GET.get("page")
    listings = p.get_page(page)

    return render(request, "auctions/index.html", {
        "listings": listings,
    })


def closed_listings(request):
    listings = Auction.objects.all()
    listings = listings.filter(active = False)
    listings = listings.order_by("-date_created").all()
    return render(request, "auctions/closed_listings.html", {
        "listings": listings
    })


# Create listing
def create_listing(request):
    if request.method == "POST":
        form = AuctionForm(request.POST, request.FILES)
        files = request.FILES.getlist("image")
        if form.is_valid():
            listing = form.save(commit=False)
            listing.product_owner = request.user
            listing.save()
            for i in files:
                Image.objects.create(auction=listing, image=i)

            return HttpResponseRedirect(reverse ('auctions:index'))
    else:
        form = AuctionForm()
        imageform = ImageForm()

    return render(request, "auctions/create_listing.html", {
        "form": form,
        "imageform": imageform,
    })



def listing_item(request, listing_id):
    listing = Auction.objects.get(pk=listing_id)
    comments = listing.comments.all()
    total_comment_likes = ""
    total_comment_dislikes = ""
    for comment in comments:
        total_comment_likes = comment.total_likes()
        total_comment_dislikes = comment.total_dislikes()
    auction_user = request.user.id
    watchlist_ids = []
    watchlist_all = Watchlist.objects.filter(watchlist_user=auction_user)
    for item in watchlist_all:
        watchlist_ids.append(item.watchlist_item.id)

    if 'add_comment' in request.POST:
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.product = Auction.objects.get(pk=listing.id)
            comment.name = request.user
            parent_id = request.POST.get('parent_id')
            if parent_id == "":
                comment.save()
            else:
                comment.parent = Comment.objects.get(id=parent_id)
                comment.save()

            return HttpResponseRedirect(reverse ('auctions:listing_item', args=(str(listing_id),)))

    elif 'add_bid' in request.POST:
        bid_form = BidForm(request.POST)
        if bid_form.is_valid():
            if listing.highest_bid:
                current_bid = listing.highest_bid
            else:
                current_bid = listing.starting_bid

            bid = bid_form.save(commit=False)
            bid.auction_biding = Auction.objects.get(pk=listing.id)
            bid.bidder = request.user
            bid.new_bid = bid_form['new_bid'].value()
            if int(bid.new_bid) > int(current_bid):
                bid.save()
                listing.highest_bid = bid.new_bid
                listing.save()
                messages.success(request, ("Your Bid Is Currently The Highest Bid"))

            else:
                messages.success(request, ("Your Bid Is Not Big Enough"))

            return HttpResponseRedirect(reverse ('auctions:listing_item', args=(str(listing_id),)))

    else:
        form = CommentForm()
        bid_form = BidForm()

    return render(request, "auctions/listing_item.html", {
        "listing": listing,

        "form": form,
        "bid_form": bid_form,
        "watchlist_all": watchlist_all,
        "watchlist_ids": watchlist_ids,
        "auction_user": auction_user,
        "total_comment_likes": total_comment_likes,
        "total_comment_dislikes": total_comment_dislikes,
    })


# Like comments
def like_comment(request, pk):
    comment = get_object_or_404(Comment, id=request.POST.get('comment_id'))
    comment.likes.add(request.user)
    listing_id = comment.product.id
    return HttpResponseRedirect(reverse ('auctions:listing_item', args=(str(listing_id),)))


# Dislike comments
def dislike_comment(request, pk):
    comment = get_object_or_404(Comment, id=request.POST.get('comment_id'))
    comment.dislikes.add(request.user)
    listing_id = comment.product.id
    return HttpResponseRedirect(reverse ('auctions:listing_item', args=(str(listing_id),)))


# Add item to a watchlist
def watchlist(request):
    if request.method == "POST":
        if request.user.is_authenticated:
            me = request.user.id
            auction_user = User.objects.get(pk=me)
            product = int(request.POST.get("watchlist_product", False))
            auction_product = Auction.objects.get(pk=product)
            watchlist_item = Watchlist.objects.create(watchlist_user=auction_user, watchlist_item=auction_product)
            watchlist_item.save()
            watchlist_all = Watchlist.objects.filter(watchlist_user=auction_user)
            return HttpResponseRedirect(reverse ('auctions:watchlist'))

    else:
        if request.user.is_authenticated:
            auction_user = request.user.id
            watchlist_all = Watchlist.objects.filter(watchlist_user=auction_user, watchlist_item__active = True)
            return render(request, 'auctions/watchlist.html', {
                "watchlist_all": watchlist_all,
                "message": "Your Watchlist Is Empty",
            })

    return render(request, 'auctions/watchlist.html', {
        "watchlist_all": watchlist_all,
    })


# Remove item from a watchlist
def remove_item(request, item_id):
    auction_item = Auction.objects.get(pk=item_id)
    if request.user.is_authenticated:
        watchlist_remove = Watchlist.objects.filter(watchlist_item = auction_item)
        watchlist_remove.delete()
        messages.success(request, ("Item Removed!"))
        return redirect('auctions:watchlist')
    else:
        messages.success(request, ("You aren't Authorized To Remove This Item!"))
        return redirect('auctions:watchlist')



# Disable listing
def disable_listing(request, listing_id):
    auction_item = Auction.objects.get(pk=listing_id)
    if request.user.is_authenticated:
        auction_item.active = False
        auction_item.date_closed = datetime.datetime.now()
        auction_item.save()
        messages.success(request, ("Listing Closed!"))
        return HttpResponseRedirect(reverse ('auctions:listing_item', args=(str(listing_id),)))
    else:
        messages.success(request, ("You aren't Authorized To Remove This Item!"))



def category(request, cat):
    category_list = Auction.objects.filter(product_category=cat)
    category_list = category_list.order_by("-date_created").all()
    return render(request, "auctions/category.html", {
        "cat": cat,
        "category_list": category_list,
    })


def search_listing(request):
    if request.method == "POST":
        searched = request.POST["searched"]
        searched_item = Auction.objects.filter(product_name__contains=searched)
        searched_item = searched_item.order_by("-date_created").all()
        return render(request, "auctions/search_listing.html", {
            "searched": searched,
            "searched_item": searched_item,
        })

    else:
        return render(request, 'auctions/search_listing.html', {})


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("auctions:index"))
    else:
        return render(request, "auctions/register.html")

commerce/auctions/templates/auctions/listing_item.html
{% extends "auctions/layout.html" %}
{% load static %}
{% load humanize %}

{% load crispy_forms_tags %}


{% block script %}
<script>
document.addEventListener('DOMContentLoaded', function() {

  var comment_div = document.querySelector(".comment-div")
  var reply_div = document.querySelectorAll(".reply-div")


  document.querySelector("#comment_submit").disabled = true;

  document.querySelectorAll(".reply_submit").forEach(function(reply_button) {
    reply_button.disabled = true;
  })

  var comment = document.getElementsByClassName("comment_form");
  for (var n = 0; n < comment.length; n++) {
    comment[n].addEventListener("keyup", event => {
      const com = event.target;
      if (com.value.length > 0){
        if (comment_div.contains(com)){
          document.querySelector("#comment_submit").disabled = false;
        }
      } else {
        document.querySelector("#comment_submit").disabled = true;
      }

      reply_div.forEach(function(single_reply) {
        if (com.value.length > 0) {
          if (single_reply.contains(com)) {
            document.querySelectorAll(".reply_submit").forEach(function(reply_button) {
              reply_button.disabled = false;
            })
          }
        } else {
          document.querySelectorAll(".reply_submit").forEach(function(reply_button) {
            reply_button.disabled = true;
          })
        }
      })

    });
  };


});


</script>
{% endblock %}


{% block body %}


    <h2>{{ listing }}</h2>
    <br>

    <div class="card mb-3" style="max-width: 1000px; display: flex; justify-content: center; margin:auto">
      <div class="row no-gutters">
        <div class="col-md-6">

          {% if listing.auction_images.all %}
    <div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
      <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>

      </div>
      <div class="carousel-inner">
        {% for image in listing.auction_images.all %}
        <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}" id="slide{{ forloop.counter }}">
          <img style="object-fit: contain; padding: 5% 5% 5% 5%; vertical-align: middle;" src="{{ image.image.url }}" class="d-block w-100" alt="...">
        </div>
        {% endfor %}
      </div>
      <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </button>
      <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </button>
    </div>
    {% endif %}


        </div>
        <div class="col-md-4">
          <div class="card-body">
            <h5 class="card-title">{{ listing }}</h5>
            <p class="card-text">{{ listing.description|linebreaks }}</p>
            {% if listing.active == True %}
            <p class="card-text"><small class="text-muted">Created: {{ listing.date_created }}</small></p>
            {% if listing.highest_bid %}
            <p class="card-text"><p class="text-muted " style="font-size: 17px;">Price: <strong>${{ listing.highest_bid|floatformat:2|intcomma }}</strong></p></p>
            {% else %}
            <p class="card-text"><p class="text-muted" style="font-size: 17px;">Price: <strong>${{ listing.starting_bid|floatformat:2|intcomma }}</strong></p></p>
            {% endif %}
            <p class="card-text">
              <p class="text-muted" style="font-size: 17px;">Details:</p>

              <ul class="text-muted" style="font-size: 15px;">
                {% if listing.product_owner %}
                <li>Listed by {{ listing.product_owner }}</li>
                {% endif %}

                {% if listing.product_category %}
                <li>Category: {{ listing.product_category|title }}</li>
                {% else %}
                No Category Listed
                {% endif %}
              {% else %}
                <p class="card-text"><small class="text-muted">Closed: {{ listing.date_closed }}</small></p>
                {% if listing.highest_bid %}
                <p class="card-text"><p class="text-muted " style="font-size: 17px;">Highest Bid: <strong>${{ listing.highest_bid }}</strong></p></p>
                {% if listing.auction_bid.all %}
                {% for bid in listing.auction_bid.all %}
                <p class="card-text"><p class="text-muted " style="font-size: 17px;">Highest Bidder: <strong>{{ bid.bidder }}</strong></p></p>
                {% endfor %}
                {% endif %}
                {% else %}
                <p class="card-text"><p class="text-muted" style="font-size: 17px;">Price: <strong>${{ listing.starting_bid }}</strong></p></p>
                {% endif %}
              {% endif %}
              </ul>
            </p>


            <h2>{{watchlist_all.watchlist_item.id}}</h2>

            {% if user.is_authenticated %}
            {% if listing.active == True %}
            <form action="{% url 'auctions:watchlist' %}" method=POST>
              {% csrf_token %}
              <br>
              <input type="hidden" name="watchlist_product" value="{{ listing.id }}">

              {% if listing.id in watchlist_ids %}
              <input type="submit" disabled value="&hearts; Add To Watchlist" class="btn" style="background-color: #48d1cc; color: white; ">
              <a href="{% url 'auctions:remove_item' listing.id %}" class="btn" style="background-color: #48d1cc; color: white; "><i class="fa-solid fa-trash fa-xs"></i> Remove</a>

              {% elif auction_user == listing.product_owner.id %}
              <input type="submit" disabled value="&hearts; Add To Watchlist" class="btn" style="background-color: #48d1cc; color: white; ">

              {% else %}
               <input type="submit" value="&hearts; Add To Watchlist" class="btn" style="background-color: #48d1cc; color: white; ">
              {% endif %}
              {% endif %}


            </form>

            {% endif %}
            <br>


            {% if user.is_authenticated %}
            {% if listing.active == True %}
            {% if auction_user == listing.product_owner.id %}
            <a href="{% url 'auctions:disable_listing' listing.id %}" class="btn" style="background-color: #48d1cc; color: white; "><span class="glyphicon glyphicon-trash"></span>Close Listing</a>
            {% else %}
            <form action="" method=POST>
              {% csrf_token %}
              <br>
              {{ bid_form.as_p }}
              <input type="submit" name = "add_bid" value="Place Bid" class="btn" style="background-color: #48d1cc; color: white; " min="{{ current_bid }}">
            </form>

            {% endif %}
            {% endif %}
            {% endif %}

            <br>
          </div>
        </div>
      </div>

      <hr>
      <br>

      <!-- Add comments container -->

      {% if user.is_authenticated  %}
      {% if listing.active == True %}
      <div class="container">
        <div class="row justify-content-md-center">
          <div class="col-sm-11">
            <form action="", method="POST">
              {% csrf_token %}
              <div class="comment-div">
              {{ form|crispy }}<br></div>
              <input type="submit" id="comment_submit" name="add_comment" value="Add Comment" class="btn" style="background-color: #48d1cc; color: white;"><br>
              <input type="hidden" name="parent_id" value="">

            </form>
          </div>
        </div>
      </div>
      {% endif %}

      {% else %}
      {% if listing.active == True %}
      <div class="container">
        <div class="row justify-content-md-center">
          <div class="col-sm-11">
            To Add comments: <a href="{% url 'auctions:login' %}">Log In here.</a>
          </div>
        </div>
      </div>

      {% endif %}
      {% endif %}

      <br>

      <!-- Comments container -->
      <div class="container">
        <div class="row justify-content-md-center">
        <div class="col-sm-11">
        <div class="card">
          <h5 class="card-header text-muted">Comments...</h5>


          {% if listing.comments.all %}
          {% load mptt_tags %}
          <div>
            {% recursetree listing.comments.all %}

            <div class="card-body border rounded" style="border-color:#d9d9d9 !important;">
              <div style="display: flex;" class="border-bottom border-2" style="border-color:#d9d9d9 !important;">

                {% if request.user.profile_picture %}
                <img src="{{ request.user.profile_picture.url }}" width="50" height="50" style="margin-right:20px;" class="rounded-circle">
                {% else %}
                <img src="{% static 'auctions/images/default-avatar-profile-icon.jpg' %}" width="50" height="50" style="margin-right:20px;" class="rounded-circle">
                {% endif %}
                <div class="justify-content-center d-flex align-items-center">
                  <div>
                    <div class="card-title text-muted">{{ node.name }}</div>
                    <div class="card-title text-muted">{{ node.date_added }}</div>
                  </div>
                </div>
              </div>
            <p class="card-text"  style="font-size: 17px;">{{ node.body }}</p>



            <div style="display: flex;">

              <form action="{% url 'auctions:like_comment' node.id %}" method="POST" style="margin-right:10px;">
                {% csrf_token %}
                <button type="submit" name="comment_id" value="{{ node.id }}" style="color: #48d1cc; border: 0; background-color: transparent;"><i class="fa-solid fa-thumbs-up"></i></button> {{ node.total_likes }}
              </form>

              <form action="{% url 'auctions:dislike_comment' node.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" name="comment_id" value="{{ node.id }}" style="color: #48d1cc; border: 0; background-color: transparent;"><i class="fa-solid fa-thumbs-down"></i></button> {{ node.total_dislikes }}
              </form>
              </div>
              <br>

              <div class="dropdown">
                <button type="button" id="reply" class="reply btn dropdown-toggle btn-sm" style="background-color: #48d1cc; color: white;" data-bs-toggle="dropdown" aria-expanded="false" data-bs-auto-close="outside">
                  Reply
                </button>
                {% if user.is_authenticated  %}
              {% if listing.active == True %}
              <form class="dropdown-menu p-4" action="", method="POST">
                <div class="reply-div">
                {% csrf_token %}
                {{ form|crispy }}<br></div>
                <input type="hidden" name="parent_id" value="{{ node.id }}">
                <input type="hidden" name="comment_id" value="{{ listing.comment.id }}">

                <input type="submit" id="reply_submit" name="add_comment" value="Reply" class="reply_submit btn" style="background-color: #48d1cc; color: white; "><br>

              </form>
              {% endif %}
              {% endif %}




              </div>

            </div>
              {% if not node.is_leaf_node %}
                <ul class="children pl-2 pl-md-5">
                  {{ children }}
                </ul>
              {% endif %}


            {% endrecursetree %}

          </div>

        </div>
      </div>
      </div>
      </div>

      {% else %}

      <div class="card-body">
        <h5 class="card-title text-muted" style="font-size: 17px;">There are no comments.</h5>
      </div>

      {% endif %}

{% endblock %}






commerce/auctions/templates/auctions/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'auctions:index' %}">Active Listings</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'auctions:watchlist' %}">Watchlist</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'auctions:create_listing' %}">Create Listing</a>
        </li>

        {% endif %}






        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu dropdown-menu-dark">

            {% for category in categories %}
            <li><a class="dropdown-item" href="{% url 'auctions:category' category %}">{{ category|title }}</a></li>
            {% endfor %}

          </ul>
        </li>

        {% if user.is_authenticated %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'auctions:closed_listings' %}">Closed Listings</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
        </li>

        {% else %}

        <li class="nav-item">
          <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
        </li>

        {% endif %}



      </ul>
      <form class="d-flex" method=POST action="{% url 'auctions:search_listing' %}">
        {% csrf_token %}
        <input class="form-control me-2" type="search" placeholder="Search Listing" aria-label="Search" name="searched">
        <button class="btn btn-outline-secondary" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

<div>
    {% if user.is_authenticated %}
        Signed in as <strong>{{ user.username }}</strong>.
    {% else %}
        Not signed in.
    {% endif %}
</div>